# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lm',
                'doc_host': 'https://numb3r33.github.io',
                'git_url': 'https://github.com/numb3r33/lm',
                'lib_path': 'lm'},
  'syms': {'lm.core': {'lm.core.foo': ('core.html#foo', 'lm/core.py')}}}
